###
GET http://127.0.0.1:5000/users HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzgzNzEwMTUsIm5iZiI6MTU3ODM3MTAxNSwianRpIjoiNTU1NGM0ZTQtYzY4Ni00Nzc4LTk2YzQtNzQ0MGM1N2RjMjZiIiwiZXhwIjoxNTc4MzgxODE1LCJpZGVudGl0eSI6ImFkbWluIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwiVXNlciI6eyJpZCI6MX19.GEDjvIfZFeeXb9LCbNkxz9Vsl_B1BFK_T0r5JvFPTSs

###
GET http://127.0.0.1:5000/users/2 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzgzNzEwMTUsIm5iZiI6MTU3ODM3MTAxNSwianRpIjoiNTU1NGM0ZTQtYzY4Ni00Nzc4LTk2YzQtNzQ0MGM1N2RjMjZiIiwiZXhwIjoxNTc4MzgxODE1LCJpZGVudGl0eSI6ImFkbWluIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwiVXNlciI6eyJpZCI6MX19.GEDjvIfZFeeXb9LCbNkxz9Vsl_B1BFK_T0r5JvFPTSs

###
POST http://127.0.0.1:5000/users HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzgzNzEwMTUsIm5iZiI6MTU3ODM3MTAxNSwianRpIjoiNTU1NGM0ZTQtYzY4Ni00Nzc4LTk2YzQtNzQ0MGM1N2RjMjZiIiwiZXhwIjoxNTc4MzgxODE1LCJpZGVudGl0eSI6ImFkbWluIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwiVXNlciI6eyJpZCI6MX19.GEDjvIfZFeeXb9LCbNkxz9Vsl_B1BFK_T0r5JvFPTSs
content-type: application/json

{
  "full_name": "John Doe",
  "department": "Engineering",
  "email":"test@sample.com",
  "position": "Engineer",
  "username": "johndoe",
  "password": "mymymy"
}

###
PATCH http://127.0.0.1:5000/users/1 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzgzNzEwMTUsIm5iZiI6MTU3ODM3MTAxNSwianRpIjoiNTU1NGM0ZTQtYzY4Ni00Nzc4LTk2YzQtNzQ0MGM1N2RjMjZiIiwiZXhwIjoxNTc4MzgxODE1LCJpZGVudGl0eSI6ImFkbWluIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwiVXNlciI6eyJpZCI6MX19.GEDjvIfZFeeXb9LCbNkxz9Vsl_B1BFK_T0r5JvFPTSs
content-type: application/json

{
  "full_name": "John Coeg",
  "department": "Marketing",
  "email":"test@sample.com",
  "position": "Sales",
  "password": "wowowoww"
}

###
DELETE http://127.0.0.1:5000/users/1 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzgzNzEwMTUsIm5iZiI6MTU3ODM3MTAxNSwianRpIjoiNTU1NGM0ZTQtYzY4Ni00Nzc4LTk2YzQtNzQ0MGM1N2RjMjZiIiwiZXhwIjoxNTc4MzgxODE1LCJpZGVudGl0eSI6ImFkbWluIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwiVXNlciI6eyJpZCI6MX19.GEDjvIfZFeeXb9LCbNkxz9Vsl_B1BFK_T0r5JvFPTSs

###
POST http://127.0.0.1:5000/users HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzgzNzEwMTUsIm5iZiI6MTU3ODM3MTAxNSwianRpIjoiNTU1NGM0ZTQtYzY4Ni00Nzc4LTk2YzQtNzQ0MGM1N2RjMjZiIiwiZXhwIjoxNTc4MzgxODE1LCJpZGVudGl0eSI6ImFkbWluIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwiVXNlciI6eyJpZCI6MX19.GEDjvIfZFeeXb9LCbNkxz9Vsl_B1BFK_T0r5JvFPTSs
content-type: application/json

{
  "username": "admin",
  "password": "admin",
  "full_name": "John Doe",
  "department": "Engineering",
  "position": "Engineer",
  "email": "support@example.com"
}

###
POST http://127.0.0.1:5000/login HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzgzNzEwMTUsIm5iZiI6MTU3ODM3MTAxNSwianRpIjoiNTU1NGM0ZTQtYzY4Ni00Nzc4LTk2YzQtNzQ0MGM1N2RjMjZiIiwiZXhwIjoxNTc4MzgxODE1LCJpZGVudGl0eSI6ImFkbWluIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwiVXNlciI6eyJpZCI6MX19.GEDjvIfZFeeXb9LCbNkxz9Vsl_B1BFK_T0r5JvFPTSs
content-type: application/json

{
  "username": "admin",
  "password": "admin"
}

###
GET http://127.0.0.1:5000/users HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzgzNzEwMTUsIm5iZiI6MTU3ODM3MTAxNSwianRpIjoiNTU1NGM0ZTQtYzY4Ni00Nzc4LTk2YzQtNzQ0MGM1N2RjMjZiIiwiZXhwIjoxNTc4MzgxODE1LCJpZGVudGl0eSI6ImFkbWluIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwiVXNlciI6eyJpZCI6MX19.GEDjvIfZFeeXb9LCbNkxz9Vsl_B1BFK_T0r5JvFPTSs

###
POST http://127.0.0.1:5000/logout/refresh HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzgzNzEwMTUsIm5iZiI6MTU3ODM3MTAxNSwianRpIjoiMDczNzU4YjUtN2I3Zi00ZWEwLTlmYWQtNWE1NGEzNGFkNDBjIiwiZXhwIjoxNTc4OTc1ODE1LCJpZGVudGl0eSI6ImFkbWluIiwidHlwZSI6InJlZnJlc2gifQ.lxXBMXSBk6gWkRBpi2ALiLpu9QSpNBtlUQUKT0G3p0A

###
POST http://127.0.0.1:5000/logout/access HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzgzNzEwMTUsIm5iZiI6MTU3ODM3MTAxNSwianRpIjoiNTU1NGM0ZTQtYzY4Ni00Nzc4LTk2YzQtNzQ0MGM1N2RjMjZiIiwiZXhwIjoxNTc4MzgxODE1LCJpZGVudGl0eSI6ImFkbWluIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwiVXNlciI6eyJpZCI6MX19.GEDjvIfZFeeXb9LCbNkxz9Vsl_B1BFK_T0r5JvFPTSs



###
GET http://127.0.0.1:5000/sites HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzgzNzEwMTUsIm5iZiI6MTU3ODM3MTAxNSwianRpIjoiNTU1NGM0ZTQtYzY4Ni00Nzc4LTk2YzQtNzQ0MGM1N2RjMjZiIiwiZXhwIjoxNTc4MzgxODE1LCJpZGVudGl0eSI6ImFkbWluIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwiVXNlciI6eyJpZCI6MX19.GEDjvIfZFeeXb9LCbNkxz9Vsl_B1BFK_T0r5JvFPTSs

###
POST http://127.0.0.1:5000/sites HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzgzNzEwMTUsIm5iZiI6MTU3ODM3MTAxNSwianRpIjoiNTU1NGM0ZTQtYzY4Ni00Nzc4LTk2YzQtNzQ0MGM1N2RjMjZiIiwiZXhwIjoxNTc4MzgxODE1LCJpZGVudGl0eSI6ImFkbWluIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwiVXNlciI6eyJpZCI6MX19.GEDjvIfZFeeXb9LCbNkxz9Vsl_B1BFK_T0r5JvFPTSs
content-type: application/json

{
  "site_name": "TA03",
  "city": "Tangerang",
  "site_address": "Ciledug",
  "longitude": 60.2375,
  "latitude": -115.3239,
  "number_of_string": 4,
  "total_capacity": 600.52
}

###
GET http://127.0.0.1:5000/sites/1 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzgzNzEwMTUsIm5iZiI6MTU3ODM3MTAxNSwianRpIjoiNTU1NGM0ZTQtYzY4Ni00Nzc4LTk2YzQtNzQ0MGM1N2RjMjZiIiwiZXhwIjoxNTc4MzgxODE1LCJpZGVudGl0eSI6ImFkbWluIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwiVXNlciI6eyJpZCI6MX19.GEDjvIfZFeeXb9LCbNkxz9Vsl_B1BFK_T0r5JvFPTSs


###
GET http://127.0.0.1:5000/strings HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzgzNzEwMTUsIm5iZiI6MTU3ODM3MTAxNSwianRpIjoiNTU1NGM0ZTQtYzY4Ni00Nzc4LTk2YzQtNzQ0MGM1N2RjMjZiIiwiZXhwIjoxNTc4MzgxODE1LCJpZGVudGl0eSI6ImFkbWluIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwiVXNlciI6eyJpZCI6MX19.GEDjvIfZFeeXb9LCbNkxz9Vsl_B1BFK_T0r5JvFPTSs

###
GET http://127.0.0.1:5000/strings?site_id=1 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzgzNzEwMTUsIm5iZiI6MTU3ODM3MTAxNSwianRpIjoiNTU1NGM0ZTQtYzY4Ni00Nzc4LTk2YzQtNzQ0MGM1N2RjMjZiIiwiZXhwIjoxNTc4MzgxODE1LCJpZGVudGl0eSI6ImFkbWluIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwiVXNlciI6eyJpZCI6MX19.GEDjvIfZFeeXb9LCbNkxz9Vsl_B1BFK_T0r5JvFPTSs

###
POST http://127.0.0.1:5000/strings HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzgzNzEwMTUsIm5iZiI6MTU3ODM3MTAxNSwianRpIjoiNTU1NGM0ZTQtYzY4Ni00Nzc4LTk2YzQtNzQ0MGM1N2RjMjZiIiwiZXhwIjoxNTc4MzgxODE1LCJpZGVudGl0eSI6ImFkbWluIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwiVXNlciI6eyJpZCI6MX19.GEDjvIfZFeeXb9LCbNkxz9Vsl_B1BFK_T0r5JvFPTSs
content-type: application/json

{
  "string_number": 4,
  "site_id": 1,
  "manufacturer": "Pilot",
  "part_number": "PBAT600-12",
  "number_of_cells": 4
}

###
GET http://127.0.0.1:5000/strings/4 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzgzNzEwMTUsIm5iZiI6MTU3ODM3MTAxNSwianRpIjoiNTU1NGM0ZTQtYzY4Ni00Nzc4LTk2YzQtNzQ0MGM1N2RjMjZiIiwiZXhwIjoxNTc4MzgxODE1LCJpZGVudGl0eSI6ImFkbWluIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwiVXNlciI6eyJpZCI6MX19.GEDjvIfZFeeXb9LCbNkxz9Vsl_B1BFK_T0r5JvFPTSs

###
DELETE http://127.0.0.1:5000/strings/3 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzgzNzEwMTUsIm5iZiI6MTU3ODM3MTAxNSwianRpIjoiNTU1NGM0ZTQtYzY4Ni00Nzc4LTk2YzQtNzQ0MGM1N2RjMjZiIiwiZXhwIjoxNTc4MzgxODE1LCJpZGVudGl0eSI6ImFkbWluIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwiVXNlciI6eyJpZCI6MX19.GEDjvIfZFeeXb9LCbNkxz9Vsl_B1BFK_T0r5JvFPTSs


###
GET http://127.0.0.1:5000/cells HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzgzNzEwMTUsIm5iZiI6MTU3ODM3MTAxNSwianRpIjoiNTU1NGM0ZTQtYzY4Ni00Nzc4LTk2YzQtNzQ0MGM1N2RjMjZiIiwiZXhwIjoxNTc4MzgxODE1LCJpZGVudGl0eSI6ImFkbWluIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwiVXNlciI6eyJpZCI6MX19.GEDjvIfZFeeXb9LCbNkxz9Vsl_B1BFK_T0r5JvFPTSs

###
GET http://127.0.0.1:5000/cells?string_id=2 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzgzNzEwMTUsIm5iZiI6MTU3ODM3MTAxNSwianRpIjoiNTU1NGM0ZTQtYzY4Ni00Nzc4LTk2YzQtNzQ0MGM1N2RjMjZiIiwiZXhwIjoxNTc4MzgxODE1LCJpZGVudGl0eSI6ImFkbWluIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwiVXNlciI6eyJpZCI6MX19.GEDjvIfZFeeXb9LCbNkxz9Vsl_B1BFK_T0r5JvFPTSs

###
POST http://127.0.0.1:5000/cells HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzgzNzEwMTUsIm5iZiI6MTU3ODM3MTAxNSwianRpIjoiNTU1NGM0ZTQtYzY4Ni00Nzc4LTk2YzQtNzQ0MGM1N2RjMjZiIiwiZXhwIjoxNTc4MzgxODE1LCJpZGVudGl0eSI6ImFkbWluIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwiVXNlciI6eyJpZCI6MX19.GEDjvIfZFeeXb9LCbNkxz9Vsl_B1BFK_T0r5JvFPTSs
content-type: application/json

{
  "cell_number": 4,
  "string_id": 2,
  "site_id": 1,
  "manufacturer": "Pilot",
  "part_number": "PBAT61-12"
}





